-- AlterTable
ALTER TABLE "SlrStudy" ADD COLUMN "ambiguityType" TEXT;
ALTER TABLE "SlrStudy" ADD COLUMN "comparisonBaseline" TEXT;
ALTER TABLE "SlrStudy" ADD COLUMN "qaNotes" TEXT;
ALTER TABLE "SlrStudy" ADD COLUMN "qaQ1" INTEGER DEFAULT 0;
ALTER TABLE "SlrStudy" ADD COLUMN "qaQ2" INTEGER DEFAULT 0;
ALTER TABLE "SlrStudy" ADD COLUMN "qaQ3" INTEGER DEFAULT 0;
ALTER TABLE "SlrStudy" ADD COLUMN "qaQ4" INTEGER DEFAULT 0;
ALTER TABLE "SlrStudy" ADD COLUMN "qaQ5" INTEGER DEFAULT 0;
ALTER TABLE "SlrStudy" ADD COLUMN "qaQ6" INTEGER DEFAULT 0;
ALTER TABLE "SlrStudy" ADD COLUMN "qaQ7" INTEGER DEFAULT 0;
ALTER TABLE "SlrStudy" ADD COLUMN "qaQ8" INTEGER DEFAULT 0;
ALTER TABLE "SlrStudy" ADD COLUMN "qaTotal" INTEGER DEFAULT 0;
ALTER TABLE "SlrStudy" ADD COLUMN "qualityFramework" TEXT;
ALTER TABLE "SlrStudy" ADD COLUMN "studyContext" TEXT;
